[env]
TERM = "xterm-256color"

[font]
size = 16.0

[font.normal]
family = "FiraCode Nerd Font"

[[keyboard.bindings]]
chars = "\u001BF"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BB"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\\"
key = "Backslash"
mods = "Option"

[window]
opacity = 0.7
