font:
  normal:
    family: "Fira Code"

  size: 16.0

window:
  opacity: 0.7

key_bindings:
  - { key: Right, mods: Alt, chars: "\x1BF" }
  - { key: Left,  mods: Alt, chars: "\x1BB" }
  - { key: Yen,              chars: "\x5c"   }

env:
    TERM: xterm-256color
