[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'joshdick/onedark.vim'

[[plugins]]
repo = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'sheerun/vim-polyglot'
merged = '0'

